COLUMNS:
  customerid: object
  age: object 
  salary: object
  balance: object
  marital: object
  jobedu: object 
  targeted: object
  default: object
  housing: object
  loan: object
  contact: object 
  day: object
  month: object 
  duration: object 
  campaign: object
  pdays: object
  previous: object 
  poutcome: object 
  response: object


TARGET_COLUMN:
  name: response