artifacts_root: artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_URL : https://github.com/AbdulAlim8660/heart-disease-prediction/raw/main/heart_v2.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/heart_v2.csv
  STATUS_FILE : artifacts/data_validation/status.txt



