artifacts_root: artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_URL : https://github.com/AbdulAlim8660/heart-disease-prediction/raw/main/heart_v2.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion